// Everything the game loads, by asset-library id. All CC0 (KayKit + Kenney): the game can ship in the open-source release.
// Base set: KayKit Medieval Hexagon pack (one shared palette texture, repainted at load by src/palette.js).
NK.assets.define({
  // ground tiles (2 m hexes, top at y = 0)
  "hex-grass": "kaykit/medieval-hexagon-pack/tiles/base/hex-grass",
  "road-a": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-a",
  "road-b": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-b",
  "road-c": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-c",
  "road-d": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-d",
  "road-e": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-e",
  "road-f": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-f",
  "road-g": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-g",
  "road-m": "kaykit/medieval-hexagon-pack/tiles/roads/hex-road-m",
  "river-a": "kaykit/medieval-hexagon-pack/tiles/rivers/hex-river-a",
  "river-a-curvy": "kaykit/medieval-hexagon-pack/tiles/rivers/hex-river-a-curvy",
  "river-b": "kaykit/medieval-hexagon-pack/tiles/rivers/hex-river-b",
  "river-c": "kaykit/medieval-hexagon-pack/tiles/rivers/hex-river-c",

  // buildings (red set = the terracotta roofs after the palette pass)
  home: "kaykit/medieval-hexagon-pack/buildings/red/building-home-a-red",
  "home-b": "kaykit/medieval-hexagon-pack/buildings/red/building-home-b-red",
  townhall: "kaykit/medieval-hexagon-pack/buildings/red/building-townhall-red",
  market: "kaykit/medieval-hexagon-pack/buildings/red/building-market-red",
  windmill: "kaykit/medieval-hexagon-pack/buildings/red/building-windmill-red",
  well: "kaykit/medieval-hexagon-pack/buildings/red/building-well-red",
  lumbermill: "kaykit/medieval-hexagon-pack/buildings/red/building-lumbermill-red",
  blacksmith: "kaykit/medieval-hexagon-pack/buildings/red/building-blacksmith-red",
  stables: "kaykit/medieval-hexagon-pack/buildings/red/building-stables-red",
  bridge: "kaykit/medieval-hexagon-pack/buildings/neutral/building-bridge-a",
  grain: "kaykit/medieval-hexagon-pack/buildings/neutral/building-grain",
  dirt: "kaykit/medieval-hexagon-pack/buildings/neutral/building-dirt",
  "wall-stone": "kaykit/medieval-hexagon-pack/buildings/neutral/fence-stone-straight",

  // nature
  pine: "kaykit/medieval-hexagon-pack/decoration/nature/tree-single-a",
  "pine-round": "kaykit/medieval-hexagon-pack/decoration/nature/tree-single-b",
  stump: "kaykit/medieval-hexagon-pack/decoration/nature/tree-single-a-cut",
  "rock-a": "kaykit/medieval-hexagon-pack/decoration/nature/rock-single-a",
  "rock-b": "kaykit/medieval-hexagon-pack/decoration/nature/rock-single-b",
  "rock-c": "kaykit/medieval-hexagon-pack/decoration/nature/rock-single-c",
  "rock-d": "kaykit/medieval-hexagon-pack/decoration/nature/rock-single-d",
  "rock-e": "kaykit/medieval-hexagon-pack/decoration/nature/rock-single-e",
  reed: "kaykit/medieval-hexagon-pack/decoration/nature/waterplant-b",
  "lily-a": "kaykit/medieval-hexagon-pack/decoration/nature/waterlily-a",
  "lily-b": "kaykit/medieval-hexagon-pack/decoration/nature/waterlily-b",

  // props
  barrel: "kaykit/medieval-hexagon-pack/decoration/props/barrel",
  crate: "kaykit/medieval-hexagon-pack/decoration/props/crate-a-big",
  "crate-small": "kaykit/medieval-hexagon-pack/decoration/props/crate-b-small",
  "crate-veg": "kaykit/medieval-hexagon-pack/decoration/props/crate-long-a",
  "crate-veg-b": "kaykit/medieval-hexagon-pack/decoration/props/crate-long-b",
  "crate-bread": "kaykit/medieval-hexagon-pack/decoration/props/crate-long-c",
  haybale: "kaykit/medieval-hexagon-pack/decoration/props/haybale",
  sack: "kaykit/medieval-hexagon-pack/decoration/props/sack",
  lumber: "kaykit/medieval-hexagon-pack/decoration/props/resource-lumber",
  stones: "kaykit/medieval-hexagon-pack/decoration/props/resource-stone",
  wheelbarrow: "kaykit/medieval-hexagon-pack/decoration/props/wheelbarrow",
  bucket: "kaykit/medieval-hexagon-pack/decoration/props/bucket-water",
  boat: "kaykit/medieval-hexagon-pack/decoration/props/boat",
  trough: "kaykit/medieval-hexagon-pack/decoration/props/trough-long",
  pallet: "kaykit/medieval-hexagon-pack/decoration/props/pallet",
  flag: "kaykit/medieval-hexagon-pack/decoration/props/flag-red",
  cart: "kaykit/medieval-hexagon-pack/units/neutral/cart-merchant",
  "cart-axle-front": "kaykit/medieval-hexagon-pack/units/neutral/cart-merchant-cart-marchant-axle-front",
  "cart-axle-rear": "kaykit/medieval-hexagon-pack/units/neutral/cart-merchant-axle-rear",
  horse: "kaykit/medieval-hexagon-pack/units/neutral/horse-b",

  // small accents from sibling KayKit sets (scaled into the hex pack: see SCALE in src/palette.js)
  bench: "kaykit/dungeon-pack/bench",
  bush: "kaykit/forest-nature-pack/color3/bush-1-b-color3",
  "berry-basket": "kaykit/resource-bits/food-basket-a-berries",
  "flour-sack": "kaykit/resource-bits/food-flour",
  "log-stack": "kaykit/resource-bits/wood-log-stack",
  "dirt-plot": "kaykit/mystery-monthly-series-6/farmers/dirt-plot",
  lettuce: "kaykit/mystery-monthly-series-6/farmers/lettuce",
  coin: "kaykit/board-game-bits/coin-10-gold", // HUD icon only

  // villagers + their animation packs (KayKit rig-medium)
  "farmer-a": "kaykit/mystery-monthly-series-6/farmers/characters/farmer-a",
  "farmer-b": "kaykit/mystery-monthly-series-6/farmers/characters/farmer-b",
  "anims-move": "kaykit/skeletons/animations/rig-medium/rig-medium-movement-basic",
  "anims-general": "kaykit/skeletons/animations/rig-medium/rig-medium-general",
  "anims-tools": "kaykit/character-animations/animations/rig-medium/rig-medium-tools",

  // audio (Kenney)
  music: "kenney/music-loops/loops/farm-frolics",
  "ui-click": "kenney/interface-sounds/click-001",
  "sfx-error": "kenney/interface-sounds/error-001",
  "sfx-place-1": "kenney/impact-sounds/impact-wood-heavy-000",
  "sfx-place-2": "kenney/impact-sounds/impact-wood-heavy-001",
  "sfx-built": "kenney/music-jingles/audio-pizzicato/jingles-pizzicato-02",
  "sfx-goal": "kenney/music-jingles/audio-pizzicato/jingles-pizzicato-00",
  "sfx-coins": "kenney/rpg-audio/handle-coins",
});
