// Generated by scripts/i18n-scopes.ts (pnpm i18n:scopes). Do not edit.
// The message areas each <ScopedIntl segment="…"> sends to the browser.
export const SCOPES = {
  "(main)": [],
  "(main)/account": ["account", "common", "nav"],
  "(main)/admin": ["account", "admin", "common", "nav", "reseller"],
  "(main)/billing": ["account", "billing", "common", "nav"],
  "(main)/dashboard": ["account", "apps", "common", "nav", "project", "studio"],
  "(main)/designer": ["account", "common", "designer", "nav"],
  "(main)/forgot-password": ["account", "auth", "common", "nav"],
  "(main)/help": ["account", "common", "helpui", "nav"],
  "(main)/login": ["account", "auth", "common", "nav"],
  "(main)/new": ["account", "ai", "apps", "catalog", "common", "nav", "studio"],
  "(main)/page": ["account", "common", "landing", "nav"],
  "(main)/projects/[id]": ["account", "apps", "common", "nav", "project"],
  "(main)/projects/[id]/data": ["common", "data"],
  "(main)/projects/[id]/flows": ["common", "flows"],
  "(main)/projects/[id]/modules": ["catalog", "studio"],
  "(main)/projects/[id]/pages/[pageId]/edit": ["ai", "catalog", "common", "editor", "studio"],
  "(main)/reseller": ["account", "admin", "common", "nav", "reseller"],
  "(main)/set-password": ["account", "auth", "common", "nav"],
  "(main)/signup": ["account", "auth", "common", "nav"],
  "install": ["install"],
} as const satisfies Record<string, readonly string[]>;

export type ScopeId = keyof typeof SCOPES;
