import { db } from "@/lib/db";
import { publishedAppUrl } from "@/lib/native";
import { getCurrentUser } from "@/lib/auth";
import { json } from "@/lib/utils";

/**
 * Downloadable "installers" for a published app. Nothing is installed in
 * the traditional sense — each script creates Desktop (+ Start Menu on
 * Windows) shortcuts that launch the published URL as an app-style window:
 *
 *   windows → .bat that writes .lnk shortcuts targeting Edge/Chrome in
 *             --app mode (both browsers ship or are common on Windows);
 *             falls back to a plain .url file if neither is found.
 *   mac     → .command that builds a minimal .app bundle on the Desktop
 *             whose executable opens the URL in the default browser.
 *
 * Phones don't need a file: the published app already serves a PWA
 * manifest + service worker, so "Add to Home Screen" does the job (the
 * publish tab shows a QR for that), and the Mobile App tab builds real
 * APKs.
 */

function sanitizeName(name: string): string {
  // Strip filesystem-hostile characters; keep it human.
  return name.replace(/[\\/:*?"<>|]/g, "").trim() || "My App";
}

function windowsInstaller(appName: string, url: string): string {
  const name = sanitizeName(appName);
  return `@echo off
rem ${name} — desktop shortcut installer (generated by Nullkode)
rem Creates Desktop + Start Menu shortcuts that open the app in its own window.
setlocal

set "APPURL=${url}"
set "APPNAME=${name}"

set "BROWSER="
if exist "%ProgramFiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe" set "BROWSER=%ProgramFiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe"
if exist "%ProgramFiles%\\Microsoft\\Edge\\Application\\msedge.exe" set "BROWSER=%ProgramFiles%\\Microsoft\\Edge\\Application\\msedge.exe"
if exist "%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe" set "BROWSER=%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe"
if exist "%LocalAppData%\\Google\\Chrome\\Application\\chrome.exe" set "BROWSER=%LocalAppData%\\Google\\Chrome\\Application\\chrome.exe"

if defined BROWSER (
  powershell -NoProfile -Command ^
    "$ws = New-Object -ComObject WScript.Shell;" ^
    "foreach ($dir in @([Environment]::GetFolderPath('Desktop'), [Environment]::GetFolderPath('StartMenu') + '\\Programs')) {" ^
    "  $lnk = $ws.CreateShortcut((Join-Path $dir ($env:APPNAME + '.lnk')));" ^
    "  $lnk.TargetPath = $env:BROWSER;" ^
    "  $lnk.Arguments = '--app=' + $env:APPURL;" ^
    "  $lnk.Description = $env:APPNAME;" ^
    "  $lnk.Save();" ^
    "}"
  echo Installed: "%APPNAME%" shortcuts added to your Desktop and Start Menu.
) else (
  rem No Edge/Chrome found — plain internet shortcut opens the default browser.
  (
    echo [InternetShortcut]
    echo URL=%APPURL%
  ) > "%UserProfile%\\Desktop\\%APPNAME%.url"
  echo Installed: "%APPNAME%" link added to your Desktop.
)

echo.
echo You can delete this installer file now.
pause
`;
}

function macInstaller(appName: string, url: string): string {
  const name = sanitizeName(appName);
  return `#!/bin/bash
# ${name} — desktop app installer (generated by Nullkode)
# Builds a minimal .app on your Desktop that opens the app.
set -e
APP="$HOME/Desktop/${name}.app"
mkdir -p "$APP/Contents/MacOS"
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>${name}</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>CFBundleIdentifier</key><string>com.nullkode.app</string>
  <key>CFBundlePackageType</key><string>APPL</string>
</dict></plist>
PLIST
cat > "$APP/Contents/MacOS/launch" <<'RUN'
#!/bin/bash
open "${url}"
RUN
chmod +x "$APP/Contents/MacOS/launch"
echo "Installed: ${name} is now on your Desktop."
echo "You can delete this installer file now."
`;
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string; platform: string }> }
) {
  const user = await getCurrentUser();
  if (!user) return json({ error: "Unauthorized" }, { status: 401 });

  const { id, platform } = await params;
  if (platform !== "windows" && platform !== "mac") {
    return json({ error: "Unknown platform" }, { status: 404 });
  }

  const project = await db.project.findUnique({
    where: { id },
    select: { id: true, name: true, slug: true, published: true, ownerId: true },
  });
  if (!project || project.ownerId !== user.id) {
    return json({ error: "Project not found" }, { status: 404 });
  }
  if (!project.published) {
    return json(
      { error: "Publish the project first — the installer points at the live URL." },
      { status: 400 }
    );
  }

  const url = await publishedAppUrl(project);
  const isWin = platform === "windows";
  const body = isWin
    ? windowsInstaller(project.name, url)
    : macInstaller(project.name, url);
  const filename = `install-${project.slug}${isWin ? ".bat" : ".command"}`;

  return new Response(body, {
    headers: {
      "content-type": "application/octet-stream",
      "content-disposition": `attachment; filename="${filename}"`,
      "cache-control": "no-store",
    },
  });
}
