/**
 * How each feature (module) is described to app owners: a plain name and one
 * line saying what it lets them or their customers do. The definitions'
 * own name/tagline/description are written for builders and stay available
 * under a card's "Details".
 */
import type { ModuleSummary } from "@/lib/modules/registry";

const NAMES: Record<string, string> = {
  auth: "Sign-in and accounts",
  "stripe-checkout": "Online payments",
  kanban: "Task board",
  leads: "Customer leads",
  "two-factor": "Extra sign-in check",
  "email-verify": "Email check",
  "webhooks-in": "Receive data from other apps",
  tags: "Labels",
  "dynamic-list": "Custom list",
  "rss-reader": "News feed reader",
  geofencer: "Location alerts",
  webview: "Show another website",
  sms: "Text messages",
  "e-wallet": "Store credit",
  "in-app-ads": "Banner ads",
  "user-groups": "Member groups",
  "channel-feed": "Video channel feed",
  "purchase-order": "Purchase orders",
  "analytics-dashboard": "Visitor stats",
  "link-tracker": "Link clicks",
  "user-favorites": "Favorites",
  "user-profile-card": "Profile card",
  "ai-assistant": "Chat helper",
};

const SUMMARIES: Record<string, string> = {
  auth: "Let people create an account and sign in to your app.",
  "food-truck-finder": "Help people find food trucks near them, with a live map.",
  "contact-form": "Let visitors send you a message.",
  newsletter: "Collect email addresses for your news and offers.",
  waitlist: "Let people sign up to hear when you open.",
  blog: "Write posts and news for your visitors.",
  faq: "Answer the questions people ask most.",
  kb: "Publish help articles your customers can search.",
  timeline: "Show your story as a list of dates and milestones.",
  portfolio: "Show off your best work.",
  testimonials: "Show what happy customers say about you.",
  guestbook: "Let visitors leave you a friendly note.",
  shop: "Sell products online with a real shopping cart.",
  catalog: "Show your products, without taking payment.",
  menu: "Show your food and drink menu.",
  pricing: "Show your prices and let people sign up.",
  coupons: "Give out discount codes.",
  wishlist: "Let people keep a list of things they want.",
  "gift-registry": "Run a wedding or baby gift list that guests can reserve from.",
  subscription: "Let customers sign up for a monthly box or plan.",
  "service-menu": "List your services with prices.",
  "quote-request": "Let customers ask you for a quote.",
  bookings: "Let people book a time with you.",
  appointments: "Let customers book an appointment with a member of your team.",
  invoice: "Send invoices and keep track of who has paid.",
  expenses: "Keep track of what your business spends.",
  properties: "List homes and properties for sale or rent.",
  rentals: "List holiday rentals people can ask to book.",
  "stripe-checkout": "Take card payments for anything you sell.",
  chat: "Give your community a shared chat room.",
  "realtime-chat": "A chat room where messages appear instantly.",
  fanwall: "Let your community post on a shared wall.",
  forum: "Let people start discussions and reply to each other.",
  reviews: "Collect star ratings and reviews from customers.",
  classifieds: "Let people post their own listings.",
  jobs: "Post job openings and receive applications.",
  team: "Introduce the people on your team.",
  polls: "Ask a question and let people vote.",
  petitions: "Collect signatures for a cause.",
  "feature-voting": "Let people suggest ideas and vote for their favorites.",
  "push-notifications": "Send alerts to people's phones and computers.",
  events: "Show upcoming events and let people say they're coming.",
  survey: "Ask customers a few questions and collect their answers.",
  quiz: "Run a fun quiz with scores.",
  todo: "Keep a to-do list and tick things off.",
  habits: "Track daily habits and build streaks.",
  journal: "Keep a daily journal with a mood for each day.",
  notes: "Jot down quick notes.",
  reading: "Keep track of books to read, being read, and finished.",
  kanban: "Move tasks across a board from to-do to done.",
  leads: "Keep track of possible customers and follow them up.",
  "help-desk": "Receive and answer customer support requests.",
  budget: "Keep track of money coming in and going out.",
  chores: "Share out household chores, with rewards.",
  wedding: "A wedding page where guests can reply to your invitation.",
  "password-vault": "Keep private notes safe behind a PIN.",
  gallery: "Show a collection of photos.",
  audio: "Share a playlist of songs or recordings.",
  video: "Show your videos from YouTube or Vimeo.",
  radio: "Play live radio stations.",
  podcast: "Share podcast episodes people can listen to.",
  recipes: "Share recipes with ingredients and steps.",
  course: "Teach an online course, lesson by lesson.",
  "ai-assistant": "Let visitors chat with a helpful assistant.",
  links: "Share a simple page of your important links.",
  places: "List local businesses or places to visit.",
  "emergency-contacts": "Keep important phone numbers one tap away.",
  weather: "Show today's weather.",
  map: "Show your locations on a map.",
  "link-tracker": "See how many people click your links.",
  "file-upload": "Let people send you files.",
  "qr-scanner": "Scan QR codes with a phone camera.",
  "user-favorites": "Let signed-in people save their favorite items.",
  "user-profile-card": "Show each signed-in person their own profile.",
  donations: "Raise money for a goal and thank your donors.",
  "lost-found": "Let your community report lost and found items.",
  "loyalty-card": "Reward regulars with a digital stamp card.",
  "e-signature": "Send a document and get it signed online.",
  "email-verify": "Check that people's email addresses are real.",
  "two-factor": "Add a code sent by email when people sign in.",
  inbox: "Let members send each other private messages.",
  referrals: "Reward people who invite their friends.",
  reminders: "Send email reminders at a time you choose.",
  tags: "Add labels to things so they're easy to sort and find.",
  "analytics-dashboard": "See how many people visit your pages.",
  "webhooks-in": "Receive information sent from other apps and services.",
  sms: "Send text messages to your customers.",
  marketplace: "Let other sellers sell through your shop.",
  inventory: "Keep track of stock and know when it's running low.",
  "e-wallet": "Give customers store credit they can top up and spend.",
  "event-tickets": "Sell tickets and check them at the door.",
  queue: "Let customers join a line without standing in it.",
  gym: "Run memberships, classes and check-ins.",
  "delivery-tracking": "Let customers follow their delivery.",
  "whatsapp-order": "Let customers send you orders on WhatsApp.",
  phonebook: "A contact list people can search.",
  claims: "Let people send a claim with a photo and follow its progress.",
  slider: "Show pictures that slide by one after another.",
  "before-after": "Compare two photos side by side with a slider.",
  "pdf-embed": "Share documents people can read on the page.",
  "status-page": "Tell customers whether everything is running normally.",
  routes: "Share a route or trip plan, stop by stop.",
  birthdays: "Wish your customers a happy birthday.",
  "scratch-card": "Give out prizes with a scratch-to-win card.",
  paywall: "Keep some pages for paying members or people with a code.",
  archive: "Keep older content searchable by year.",
  "share-app": "Make it easy for people to share your app.",
  reactions: "Let people react to posts with a quick emoji.",
  "scheduled-content": "Write now and publish later.",
  "drip-content": "Release lessons a few days apart.",
  acknowledgments: "Make sure people have read important messages.",
  leaderboard: "Show a ranking of top scores.",
  "dynamic-list": "Make your own list of anything, with a page to edit it.",
  countdown: "Count down to a launch, sale or event.",
  webview: "Show another website inside your app.",
  "rss-reader": "Show the latest posts from another website's news feed.",
  geofencer: "Show something special when people arrive at a place.",
  "personalized-dashboard": "Give each signed-in person their own home page.",
  "table-reservations": "Let guests book a table at your restaurant.",
  "member-id-card": "Give members a digital ID card.",
  "media-playlist": "Put songs and videos together in one playlist.",
  "calculator-builder": "Add a calculator, like a price or loan estimate.",
  "business-card-wallet": "Share and save digital business cards.",
  "nutrition-tracker": "Log meals and count calories.",
  "project-portfolio": "Track your projects and how far along they are.",
  "purchase-order": "Request, approve and track orders from suppliers.",
  "app-walkthrough": "Show new visitors a short tour of your app.",
  "abandoned-cart": "Remind shoppers who left items in their cart.",
  "submissions-queue": "Collect submissions and approve them before they go live.",
  "store-locator": "Help people find your nearest shop.",
  "delivery-zones": "Set delivery prices for different areas.",
  "live-stream": "Show a live video stream.",
  "channel-feed": "Show the latest videos from your YouTube or Vimeo channel.",
  "in-app-ads": "Show your own banner ads and see who clicks.",
  "user-groups": "Put members into groups, like VIP or staff.",
};

export function friendlyName(m: Pick<ModuleSummary, "id" | "name">): string {
  return NAMES[m.id] ?? m.name;
}

export function friendlySummary(m: Pick<ModuleSummary, "id" | "tagline">): string {
  return SUMMARIES[m.id] ?? m.tagline;
}

/** Config fields that name the business itself; prefilled with the app's name. */
export const BUSINESS_NAME_FIELD =
  /^(?:app|business|shop|store|restaurant|cafe|brand|agency|gym|salon|studio|clinic|company|org|organization|site|school|church|practice|firm|club|venue|hotel|spa)Name$|^brand$/i;
