// Everything the game loads, by asset-library id (CC0 only: KayKit + Kenney). Ids are written in full:
// the platform builds assets.lock.json from the string literals it finds.
// Main set: KayKit Space Base Bits. Character: KayKit Space Ranger (rig-medium clips).
// Kenney Space Kit fills gaps (dish, crystals, boulders, turret) and is normalised in src/world/materials.js.
NK.assets.define({
  // --- base modules (KayKit Space Base Bits)
  "hub": "kaykit/space-base-bits/basemodule-e",
  "module-b": "kaykit/space-base-bits/basemodule-b",
  "mod-command": "kaykit/space-base-bits/mobile-base-command",
  "mod-carriage": "kaykit/space-base-bits/mobile-base-carriage",
  "tunnel": "kaykit/space-base-bits/tunnel-straight-a",
  "dome": "kaykit/space-base-bits/dome",
  "farm": "kaykit/space-base-bits/space-farm-large",
  "pad": "kaykit/space-base-bits/landingpad-large",
  "dropship": "kaykit/space-base-bits/dropship",
  "lamp": "kenney/racing-kit/light-post-large",
  "solar": "kaykit/space-base-bits/solarpanel",
  "roof-solar": "kaykit/space-base-bits/roofmodule-solarpanels",
  "roof-base": "kaykit/space-base-bits/roofmodule-base",
  "depot": "kaykit/space-base-bits/cargodepot-a",
  "crates-a": "kaykit/space-base-bits/cargo-a-stacked",
  "crates-b": "kaykit/space-base-bits/cargo-b-stacked",
  "crate-a": "kaykit/space-base-bits/cargo-a",
  "crate-b": "kaykit/space-base-bits/cargo-b-packed",
  "barrels-blue": "kaykit/space-base-bits/containers-c",
  "barrels-yellow": "kaykit/space-base-bits/containers-b",
  "water-tank": "kaykit/space-base-bits/water-storage",
  "rover-frame": "kaykit/space-base-bits/mobile-base-frame",
  "pebble-a": "kaykit/space-base-bits/rock-a",
  "pebble-b": "kaykit/space-base-bits/rock-b",
  // --- Kenney Space Kit (normalised)
  "dish": "kenney/space-kit/satellite-dish-large",
  "crystal": "kenney/tower-defense-kit/detail-crystal",
  // --- rocks: KayKit Forest Nature Pack boulders in its taupe (colour 3, tinted mauve) and slate (colour 4) variants
  "boulder-a": "kaykit/forest-nature-pack/color3/rock-3-k-color3",
  "boulder-b": "kaykit/forest-nature-pack/color3/rock-3-i-color3",
  "boulder-c": "kaykit/forest-nature-pack/color3/rock-3-l-color3",
  "boulder-d": "kaykit/forest-nature-pack/color3/rock-3-q-color3",
  "boulder-e": "kaykit/forest-nature-pack/color3/rock-3-o-color3",
  "slate-a": "kaykit/forest-nature-pack/color4/rock-3-k-color4",
  "slate-b": "kaykit/forest-nature-pack/color4/rock-3-q-color4",
  "slate-c": "kaykit/forest-nature-pack/color4/rock-3-m-color4",
  "stones-a": "kenney/space-kit/rocks-small-a",
  "stones-b": "kenney/space-kit/rocks-small-b",
  "turret": "kenney/space-kit/turret-single",
  "generator": "kenney/space-kit/machine-generator",
  // --- people (KayKit Space Ranger + rig-medium animation packs)
  "ranger": "kaykit/mystery-monthly-series-4/space-ranger/character/space-ranger",
  "helmet": "kaykit/mystery-monthly-series-4/space-ranger/space-ranger-helmet",
  "backpack": "kaykit/mystery-monthly-series-4/space-ranger/space-ranger-jetpack",
  "anims-general": "kaykit/skeletons/animations/rig-medium/rig-medium-general",
  "anims-move": "kaykit/skeletons/animations/rig-medium/rig-medium-movement-basic",
  "anims-tools": "kaykit/character-animations/animations/rig-medium/rig-medium-tools",
  // --- sound
  "music": "kenney/music-loops/loops/space-cadet",
  "ui-click": "kenney/interface-sounds/click-001",
  "sfx-build": "kenney/sci-fi-sounds/impact-metal-001",
  "sfx-error": "kenney/interface-sounds/error-004",
  "sfx-power": "kenney/sci-fi-sounds/force-field-002",
  "sfx-send": "kenney/interface-sounds/maximize-006",
  "sfx-mine": "kenney/interface-sounds/glass-001",
  "sfx-deliver": "kenney/interface-sounds/glass-004",
  "sfx-objective": "kenney/interface-sounds/confirmation-002",
  "sfx-sol": "kenney/interface-sounds/bong-001",
  "sfx-laser": "kenney/sci-fi-sounds/laser-small-002",
  "sfx-impact": "kenney/sci-fi-sounds/low-frequency-explosion-001",
});
