/**
 * Sample guides for the Places feature, one per "Use for" choice. Every
 * place is fictional (names, phone numbers and web addresses are made up),
 * set in real Lisbon neighbourhoods with believable coordinates. Pictures
 * come only from the platform's own library (public/media/generated).
 */

type Place = {
  name: string;
  category: string;
  address: string;
  description: string;
  phone?: string;
  website?: string;
  lat: number;
  lng: number;
  image_url: string;
  gallery?: string[];
  hours?: string;
  featured?: boolean;
};

type Category = { name: string; image_url: string };

const img = (id: string) => `/media/generated/${id}.webp`;

function rows(places: Place[]): Array<Record<string, unknown>> {
  return places.map((p, i) => ({
    name: p.name,
    category: p.category,
    address: p.address,
    description: p.description,
    phone: p.phone ?? "",
    website: p.website ?? "",
    lat: p.lat,
    lng: p.lng,
    image_url: p.image_url,
    gallery: (p.gallery ?? []).join("\n"),
    hours: p.hours ?? "",
    featured: Boolean(p.featured),
    sort_order: i + 1,
    status: "approved",
    submitted_by: "",
  }));
}

function cats(list: Category[]): Array<Record<string, unknown>> {
  return list.map((c, i) => ({ name: c.name, image_url: c.image_url, sort_order: i + 1 }));
}

/* ── Tourist guide (the default) ─────────────────────────────────────── */

const TOURIST: Place[] = [
  {
    name: "Miradouro do Monte Alto",
    category: "Viewpoints",
    address: "Largo da Graça 12, 1170-165 Lisboa",
    description: "A shady hilltop terrace with one of the widest views over the old town's rooftops, the castle hill and the river. Come for sunset, when the whole city turns gold.\n\nThe vintage tram stops just below the terrace.",
    lat: 38.71705,
    lng: -9.13135,
    image_url: img("city-hilltop-viewpoint"),
    gallery: [img("city-tram-street")],
    hours: "Open all day",
    featured: true,
  },
  {
    name: "Ribeira Riverside Walk",
    category: "Waterfront",
    address: "Avenida Ribeira das Naus, 1100-038 Lisboa",
    description: "A wide stone promenade along the river, with old quays, small boats and long views to the bridge. Perfect for an evening stroll from the main square to the waterfront bars.",
    lat: 38.70655,
    lng: -9.14045,
    image_url: img("city-riverside-sunset"),
    gallery: [img("marine-marina")],
    hours: "Open all day",
    featured: true,
  },
  {
    name: "Café Azulejo",
    category: "Cafés",
    address: "Rua da Rosa 85, 1200-383 Lisboa",
    description: "A tiny café with a terrace under the trees and a facade covered in blue and white tiles. Strong coffee, custard tarts still warm from the oven and a relaxed neighbourhood crowd.",
    phone: "+351 210 000 101",
    lat: 38.71285,
    lng: -9.14505,
    image_url: img("city-tiled-cafe-terrace"),
    gallery: [img("food-flat-white"), img("food-croissant-tray")],
    hours: "Mon–Fri 8:00–19:00\nSat–Sun 9:00–18:00",
    featured: true,
  },
  {
    name: "Galeria Luz Norte",
    category: "Galleries",
    address: "Rua da Boavista 64, 1200-066 Lisboa",
    description: "A bright gallery in an old warehouse showing large paintings and sculpture by artists from Portugal and abroad. Free entry, with new shows every six weeks.",
    phone: "+351 210 000 102",
    website: "https://example.com/galeria-luz-norte",
    lat: 38.70835,
    lng: -9.14985,
    image_url: img("city-art-gallery"),
    hours: "Tue–Sat 11:00–19:00\nSun–Mon closed",
    featured: true,
  },
  {
    name: "Sala Tejo",
    category: "Music",
    address: "Rua Nova do Carvalho 32, 1200-292 Lisboa",
    description: "A small, loud and much-loved concert room near the river. Local bands, touring acts and late DJ sets most nights of the week.",
    phone: "+351 210 000 103",
    website: "https://example.com/sala-tejo",
    lat: 38.70715,
    lng: -9.14405,
    image_url: img("city-concert-venue"),
    hours: "Wed–Sun 20:00–02:00",
    featured: true,
  },
  {
    name: "Livraria Página Antiga",
    category: "Bookshops",
    address: "Rua do Carmo 70, 1200-094 Lisboa",
    description: "An independent bookshop with creaking wooden floors, a reading corner by the window and a good shelf of Portuguese writers in translation.",
    phone: "+351 210 000 104",
    lat: 38.71125,
    lng: -9.13965,
    image_url: img("bookstore-reading-corner"),
    gallery: [img("bookstore-bookseller")],
    hours: "Daily 10:00–20:00",
  },
  {
    name: "Terraço São Pedro",
    category: "Viewpoints",
    address: "Rua de São Pedro de Alcântara 1, 1250-238 Lisboa",
    description: "A rooftop terrace above the garden viewpoint, with lounge seats, string lights and a view across the valley to the castle. Drinks and small plates until late.",
    phone: "+351 210 000 105",
    lat: 38.71535,
    lng: -9.14465,
    image_url: img("city-rooftop-terrace"),
    hours: "Daily 12:00–00:00",
  },
  {
    name: "Padaria do Bairro",
    category: "Cafés",
    address: "Rua de São Bento 220, 1200-821 Lisboa",
    description: "A neighbourhood bakery that opens early: sourdough loaves, pastries and good coffee at the counter or to take away.",
    phone: "+351 210 000 106",
    lat: 38.71505,
    lng: -9.15365,
    image_url: img("food-bakery-counter"),
    gallery: [img("food-croissant-tray")],
    hours: "Mon–Sat 7:30–19:00\nSun 8:00–13:00",
  },
  {
    name: "Grão Coffee Roasters",
    category: "Cafés",
    address: "Rua Poiais de São Bento 40, 1200-347 Lisboa",
    description: "Speciality coffee roasted on site, served at a long pale counter in the morning sun. Ask about the beans of the week.",
    lat: 38.71045,
    lng: -9.14895,
    image_url: img("food-flat-white"),
    gallery: [img("portfolio-kaffebar-ro"), img("lifestyle-coffee-grinder")],
    hours: "Daily 8:00–17:00",
  },
  {
    name: "Atelier Sete Colinas",
    category: "Galleries",
    address: "Rua de São Miguel 18, 1100-544 Lisboa",
    description: "A print studio and small gallery in the old quarter. Watch prints being made and buy limited editions straight from the artists.",
    lat: 38.71135,
    lng: -9.12925,
    image_url: img("printing-print-studio"),
    gallery: [img("creative-poster-wall")],
    hours: "Tue–Sun 10:00–18:00",
  },
  {
    name: "Casa da Guitarra",
    category: "Music",
    address: "Rua de São Pedro 12, 1100-498 Lisboa",
    description: "A candlelit tavern where traditional guitar and song fill the room every evening. Book a table for dinner, or stand at the bar for a glass and a set.",
    phone: "+351 210 000 107",
    lat: 38.71145,
    lng: -9.12815,
    image_url: img("restaurant-dining-room"),
    gallery: [img("restaurant-wine-pour")],
    hours: "Tue–Sun 19:30–01:00",
  },
  {
    name: "Doca Azul",
    category: "Waterfront",
    address: "Avenida 24 de Julho 60, 1200-480 Lisboa",
    description: "A quiet riverside dock lined with seafood terraces. Watch the sailing boats come in while the sun goes down over the river.",
    lat: 38.70525,
    lng: -9.15515,
    image_url: img("marine-marina"),
    hours: "Open all day",
  },
  {
    name: "Biblioteca do Largo",
    category: "Bookshops",
    address: "Largo do Carmo 5, 1200-092 Lisboa",
    description: "A grand old reading room with floor-to-ceiling shelves and a painted ceiling, now a second-hand bookshop with rare editions and maps.",
    lat: 38.71205,
    lng: -9.14075,
    image_url: img("legal-library"),
    gallery: [img("legal-law-books")],
    hours: "Mon–Sat 10:00–19:00",
  },
];

const TOURIST_CATS: Category[] = [
  { name: "Viewpoints", image_url: img("city-hilltop-viewpoint") },
  { name: "Cafés", image_url: img("city-tiled-cafe-terrace") },
  { name: "Galleries", image_url: img("city-art-gallery") },
  { name: "Music", image_url: img("city-concert-venue") },
  { name: "Waterfront", image_url: img("city-riverside-sunset") },
  { name: "Bookshops", image_url: img("bookstore-reading-corner") },
];

/* ── Restaurants ──────────────────────────────────────────────────────── */

const RESTAURANTS: Place[] = [
  {
    name: "Brasa Viva",
    category: "Portuguese",
    address: "Rua do Alecrim 50, 1200-018 Lisboa",
    description: "Wood-fire cooking in a candlelit dining room: grilled fish, slow-roasted lamb and seasonal vegetables from the hearth. Book ahead at weekends.",
    phone: "+351 210 000 201",
    website: "https://example.com/brasa-viva",
    lat: 38.70905,
    lng: -9.14305,
    image_url: img("restaurant-dining-room"),
    gallery: [img("restaurant-embers"), img("restaurant-the-pass"), img("restaurant-lamb-rack")],
    hours: "Tue–Sat 19:00–23:30\nSun 12:30–15:30",
    featured: true,
  },
  {
    name: "Mar Salgado",
    category: "Seafood",
    address: "Rua Nova do Carvalho 10, 1200-292 Lisboa",
    description: "Fish straight from the morning market, grilled simply with olive oil and lemon, on a terrace a few steps from the river.",
    phone: "+351 210 000 202",
    lat: 38.70685,
    lng: -9.14525,
    image_url: img("food-sheet-pan-salmon"),
    gallery: [img("city-riverside-sunset")],
    hours: "Daily 12:00–23:00",
    featured: true,
  },
  {
    name: "Copo & Vista",
    category: "Wine bars",
    address: "Rua de São Pedro de Alcântara 3, 1250-238 Lisboa",
    description: "A rooftop wine bar with forty wines by the glass, cheese and charcuterie boards and a sunset view over the old town.",
    phone: "+351 210 000 203",
    lat: 38.71535,
    lng: -9.14465,
    image_url: img("city-rooftop-terrace"),
    gallery: [img("restaurant-wine-pour")],
    hours: "Daily 16:00–00:00",
    featured: true,
  },
  {
    name: "Café Azulejo",
    category: "Cafés & bakeries",
    address: "Rua da Rosa 85, 1200-383 Lisboa",
    description: "Coffee and warm custard tarts on a sunny terrace in front of a tiled facade.",
    lat: 38.71285,
    lng: -9.14505,
    image_url: img("city-tiled-cafe-terrace"),
    gallery: [img("food-flat-white")],
    hours: "Daily 8:00–19:00",
  },
  {
    name: "Pastelaria Estrela",
    category: "Cafés & bakeries",
    address: "Calçada da Estrela 92, 1200-667 Lisboa",
    description: "A family bakery known for its butter croissants and almond cakes. Arrive early: the first tray sells out by nine.",
    phone: "+351 210 000 204",
    lat: 38.71305,
    lng: -9.15905,
    image_url: img("food-croissant-tray"),
    gallery: [img("food-bakery-counter")],
    hours: "Mon–Sat 7:00–19:00",
  },
  {
    name: "Horta Verde",
    category: "Vegetarian",
    address: "Rua dos Anjos 40, 1150-039 Lisboa",
    description: "Colourful grain bowls, garden salads and soups made with vegetables from small farms outside the city.",
    lat: 38.72405,
    lng: -9.13655,
    image_url: img("food-green-grain-bowl"),
    gallery: [img("food-garden-salad"), img("food-tomato-soup")],
    hours: "Mon–Sat 12:00–22:00",
  },
  {
    name: "Massa Fresca",
    category: "Pizza & pasta",
    address: "Rua da Graça 50, 1170-165 Lisboa",
    description: "Fresh pasta made every morning and thin wood-oven pizzas. A cheerful room that fills up with families on Sunday.",
    phone: "+351 210 000 205",
    lat: 38.71805,
    lng: -9.13105,
    image_url: img("food-garlic-oil-pasta"),
    gallery: [img("food-margherita-pizza")],
    hours: "Daily 12:00–15:00, 19:00–23:00",
  },
  {
    name: "Taberna da Esquina",
    category: "Portuguese",
    address: "Rua Tomás da Anunciação 30, 1350-325 Lisboa",
    description: "A corner tavern with a short daily menu of home cooking, house bread and wine from small producers.",
    lat: 38.71835,
    lng: -9.16655,
    image_url: img("restaurant-dinner-table"),
    gallery: [img("restaurant-house-bread")],
    hours: "Mon–Sat 12:00–15:00, 19:30–23:00",
  },
];

const RESTAURANT_CATS: Category[] = [
  { name: "Portuguese", image_url: img("restaurant-dinner-table") },
  { name: "Seafood", image_url: img("food-sheet-pan-salmon") },
  { name: "Cafés & bakeries", image_url: img("food-croissant-tray") },
  { name: "Wine bars", image_url: img("restaurant-wine-pour") },
  { name: "Vegetarian", image_url: img("food-green-grain-bowl") },
  { name: "Pizza & pasta", image_url: img("food-margherita-pizza") },
];

/* ── Business directory ───────────────────────────────────────────────── */

const DIRECTORY: Place[] = [
  {
    name: "Flor de Lis",
    category: "Home & garden",
    address: "Rua de São Bento 150, 1200-821 Lisboa",
    description: "Seasonal bouquets, dried flowers and plants, arranged to order. Same-day delivery in the city centre.",
    phone: "+351 210 000 301",
    website: "https://example.com/flor-de-lis",
    lat: 38.71375,
    lng: -9.15285,
    image_url: img("florist-flower-shop"),
    hours: "Mon–Sat 9:00–19:00",
    featured: true,
  },
  {
    name: "Ótica Avenida",
    category: "Health & beauty",
    address: "Avenida da Liberdade 120, 1250-146 Lisboa",
    description: "Eye tests, contact lenses and a hand-picked range of frames from independent makers.",
    phone: "+351 210 000 302",
    lat: 38.71955,
    lng: -9.14505,
    image_url: img("eyewear-optical-store"),
    hours: "Mon–Fri 10:00–19:00\nSat 10:00–14:00",
    featured: true,
  },
  {
    name: "Bicicletaria Cais",
    category: "Services",
    address: "Rua da Cintura do Porto 8, 1200-109 Lisboa",
    description: "Bike repairs while you wait, servicing and city bikes to rent by the hour or the day.",
    phone: "+351 210 000 303",
    lat: 38.70625,
    lng: -9.14755,
    image_url: img("bicycle-cycle-workshop"),
    gallery: [img("bicycle-commuter-bike")],
    hours: "Mon–Sat 9:00–18:30",
    featured: true,
  },
  {
    name: "Barbearia Rossio",
    category: "Health & beauty",
    address: "Rua dos Sapateiros 100, 1100-577 Lisboa",
    description: "Classic cuts and hot-towel shaves in a vintage barbershop. Walk in or book online.",
    phone: "+351 210 000 304",
    lat: 38.71205,
    lng: -9.13805,
    image_url: img("barber-barber-chair"),
    gallery: [img("barber-precision-haircut")],
    hours: "Tue–Sat 10:00–20:00",
  },
  {
    name: "Livraria Página Antiga",
    category: "Shops",
    address: "Rua do Carmo 70, 1200-094 Lisboa",
    description: "An independent bookshop with a reading corner and a strong shelf of local writers.",
    lat: 38.71125,
    lng: -9.13965,
    image_url: img("bookstore-reading-corner"),
    hours: "Daily 10:00–20:00",
  },
  {
    name: "Padaria do Bairro",
    category: "Food & drink",
    address: "Rua de São Bento 220, 1200-821 Lisboa",
    description: "Sourdough loaves, pastries and coffee from early morning.",
    lat: 38.71505,
    lng: -9.15365,
    image_url: img("food-bakery-counter"),
    hours: "Mon–Sat 7:30–19:00",
  },
  {
    name: "Lavandaria Estrela",
    category: "Services",
    address: "Rua Domingos Sequeira 20, 1350-119 Lisboa",
    description: "Self-service machines, a wash-and-fold service and dry cleaning, ready the next day.",
    phone: "+351 210 000 305",
    lat: 38.71435,
    lng: -9.16225,
    image_url: img("laundry-laundry-shop"),
    hours: "Daily 7:00–22:00",
  },
  {
    name: "Contas Certas",
    category: "Professional",
    address: "Avenida da República 30, 1050-191 Lisboa",
    description: "Accounting, tax returns and payroll for small businesses and freelancers, in Portuguese and English.",
    phone: "+351 210 000 306",
    website: "https://example.com/contas-certas",
    lat: 38.73755,
    lng: -9.14555,
    image_url: img("accounting-accountant-desk"),
    hours: "Mon–Fri 9:00–18:00",
  },
  {
    name: "Ateliê do Oleiro",
    category: "Shops",
    address: "Rua dos Remédios 44, 1100-445 Lisboa",
    description: "Handmade ceramics thrown in the studio at the back: cups, bowls and vases, plus weekend classes.",
    lat: 38.71145,
    lng: -9.12755,
    image_url: img("ecommerce-wheel-hands"),
    gallery: [img("ecommerce-terracotta-tumblers")],
    hours: "Tue–Sun 11:00–19:00",
  },
];

const DIRECTORY_CATS: Category[] = [
  { name: "Shops", image_url: img("signage-blank-storefront") },
  { name: "Food & drink", image_url: img("food-bakery-counter") },
  { name: "Health & beauty", image_url: img("barber-barber-chair") },
  { name: "Services", image_url: img("bicycle-cycle-workshop") },
  { name: "Home & garden", image_url: img("florist-flower-shop") },
  { name: "Professional", image_url: img("accounting-accountant-desk") },
];

/* ── Wedding & event venues ───────────────────────────────────────────── */

const VENUES: Place[] = [
  {
    name: "Palácio das Arcadas",
    category: "Historic halls",
    address: "Rua da Escola Politécnica 56, 1250-102 Lisboa",
    description: "A restored stone hall with arched windows and timber beams, for receptions of up to 180 guests. In-house catering and a quiet garden for the ceremony.",
    phone: "+351 210 000 401",
    website: "https://example.com/palacio-das-arcadas",
    lat: 38.71705,
    lng: -9.15005,
    image_url: img("city-event-hall"),
    hours: "Visits by appointment",
    featured: true,
  },
  {
    name: "Quinta do Jardim",
    category: "Gardens",
    address: "Estrada de Monserrate, 2710-405 Sintra",
    description: "Outdoor ceremonies under old trees, a floral arch and a lawn for dinner under the stars. Forty minutes from the city.",
    phone: "+351 210 000 402",
    lat: 38.79305,
    lng: -9.41805,
    image_url: img("events-garden-wedding"),
    hours: "Visits by appointment",
    featured: true,
  },
  {
    name: "Terraço Sete Colinas",
    category: "Rooftops",
    address: "Rua de São Pedro de Alcântara 3, 1250-238 Lisboa",
    description: "A rooftop terrace for parties and small weddings, with a sunset view over the old town and the river.",
    phone: "+351 210 000 403",
    lat: 38.71535,
    lng: -9.14465,
    image_url: img("city-rooftop-terrace"),
    hours: "Events from 17:00",
    featured: true,
  },
  {
    name: "Armazém do Rio",
    category: "Waterfront",
    address: "Avenida Brasília, 1300-598 Lisboa",
    description: "A converted riverside warehouse with a terrace on the water. Big enough for 300 guests, with space for a band and a dance floor.",
    lat: 38.69905,
    lng: -9.18305,
    image_url: img("city-riverside-sunset"),
    hours: "Visits by appointment",
  },
  {
    name: "Hotel Pátio das Oliveiras",
    category: "Hotels",
    address: "Rua Frederico Arouca 40, 2750-355 Cascais",
    description: "A boutique hotel by the sea with a courtyard pool, olive trees and twenty rooms for the wedding party.",
    phone: "+351 210 000 404",
    lat: 38.69705,
    lng: -9.42155,
    image_url: img("hospitality-courtyard-pool"),
    gallery: [img("hospitality-marsh-suite")],
    hours: "Reception open 24 hours",
  },
  {
    name: "Sala Biblioteca",
    category: "Historic halls",
    address: "Largo do Carmo 5, 1200-092 Lisboa",
    description: "An old library hall with painted ceilings, for intimate dinners and civil ceremonies of up to 60 guests.",
    lat: 38.71205,
    lng: -9.14075,
    image_url: img("legal-library"),
    hours: "Visits by appointment",
  },
  {
    name: "Cais da Marina",
    category: "Waterfront",
    address: "Doca de Santo Amaro, 1350-353 Lisboa",
    description: "Drinks receptions on the pontoon and dinner in a glass pavilion by the boats.",
    lat: 38.70215,
    lng: -9.17905,
    image_url: img("marine-marina"),
    hours: "Visits by appointment",
  },
  {
    name: "Brasa Viva",
    category: "Restaurants",
    address: "Rua do Alecrim 50, 1200-018 Lisboa",
    description: "A private dining room for rehearsal dinners and small celebrations, with a wood-fire menu.",
    lat: 38.70905,
    lng: -9.14305,
    image_url: img("restaurant-dining-room"),
    gallery: [img("restaurant-dinner-table")],
    hours: "Tue–Sun from 19:00",
  },
];

const VENUE_CATS: Category[] = [
  { name: "Historic halls", image_url: img("city-event-hall") },
  { name: "Gardens", image_url: img("events-garden-wedding") },
  { name: "Rooftops", image_url: img("city-rooftop-terrace") },
  { name: "Waterfront", image_url: img("city-riverside-sunset") },
  { name: "Hotels", image_url: img("hospitality-courtyard-pool") },
  { name: "Restaurants", image_url: img("restaurant-dining-room") },
];

export const PLACE_SEEDS = {
  tourist: rows(TOURIST),
  restaurants: rows(RESTAURANTS),
  directory: rows(DIRECTORY),
  venues: rows(VENUES),
};

export const CATEGORY_SEEDS = {
  tourist: cats(TOURIST_CATS),
  restaurants: cats(RESTAURANT_CATS),
  directory: cats(DIRECTORY_CATS),
  venues: cats(VENUE_CATS),
};
