/**
 * Nullkode design system — shared between the AI scaffolder, the AI
 * inline editor, and the module authors. This is the single source of
 * truth for "what a Nullkode page should look like".
 *
 * Goal: pages generated by AI should look like premium Crafto / Litho
 * templates — elegant, personality-driven, modern — not generic Bootstrap.
 *
 * Every rule here assumes our theme system is in play: colors, fonts,
 * radii come from CSS variables on :root (set by /api/projects/:id/theme.css).
 * Pages that reference them via `var(--nk-*)` automatically re-skin
 * whenever the user picks a different theme.
 */

/**
 * The owner publishes what the AI writes as their own words, so it must not
 * make things up about the business. Shared by every builder prompt (the
 * design rules below include it; the plan, build and edit prompts repeat it).
 */
export const HONESTY_RULES = `HONEST CONTENT — the owner publishes this as their own words
- Never invent testimonials, reviews, quotes, star ratings, customer or user counts, awards, certifications, press mentions or partner logos.
- Leave statistics out unless the request supplies them: no made-up counts, percentages or years in business.
- For facts you weren't given (prices, opening hours, phone numbers, addresses, email addresses, staff names), write a clearly marked placeholder such as [Your price], [Opening hours] or [Phone number] — never a made-up value.
- Write headings and descriptions that fit the business, without claims nobody can back up ("award-winning", "trusted by thousands", "the best in town").`;

/**
 * Hard rules the AI must follow. Kept as a single string so we can
 * inject it into any prompt without restructuring each one.
 */
export const DESIGN_SYSTEM_RULES = `NULLKODE DESIGN SYSTEM — follow every rule

${HONESTY_RULES}

CORE AESTHETIC
Every page you generate should feel like a premium website template (think Crafto, Litho, Stripe, Linear). Clean. Confident. Spacious. Opinionated. Each app should have its own personality that matches its industry — a restaurant should feel warm and inviting, a SaaS should feel clean and technical, a yoga studio should feel calm and organic.

THEME TOKENS (always use these — NEVER hardcode colors, fonts, or radii)
The project has a theme exposed via CSS custom properties. Reference them instead of hex colors:
  var(--nk-primary)       primary brand color (use for CTAs, links, emphasis)
  var(--nk-primary-2)     hover/pressed state for primary
  var(--nk-accent)        secondary accent (use for highlights, badges, gradients)
  var(--nk-bg)            page background (DO NOT set on <body> — already applied)
  var(--nk-surface)       card background
  var(--nk-surface-2)     subtle surface (alt rows, muted bands)
  var(--nk-border)        divider/border color
  var(--nk-text)          body text
  var(--nk-text-muted)    secondary/metadata text
  var(--nk-radius)        card/section radius
  var(--nk-radius-sm)     input/button radius
  var(--nk-font)          body font
  var(--nk-font-display)  heading font

Use them in inline styles when you need custom colors or gradients:
  style="background: linear-gradient(135deg, var(--nk-primary), var(--nk-accent));"
  style="color: var(--nk-text-muted);"
  style="border: 1px solid var(--nk-border); border-radius: var(--nk-radius);"
Text placed directly on var(--nk-primary) uses color:var(--nk-on-primary) (white or dark, whichever is readable for this theme); on var(--nk-accent) use var(--nk-on-accent).
Never write hex colors, rgb(), or hardcoded font families in generated HTML. Never use bg-white, bg-black, text-white, text-dark, bg-primary, text-primary Bootstrap utilities — they break theming. Use var(--nk-*) instead.

TYPOGRAPHY
- Hero heading: <h1 class="display-3 fw-bold" style="letter-spacing:-0.02em;line-height:1.05;">
- Section heading: <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">
- Lead paragraph: <p class="lead" style="color: var(--nk-text-muted); max-width:620px;">
- Small metadata: <span class="small text-uppercase fw-semibold" style="color: var(--nk-text-muted); letter-spacing:0.15em;">
- Eyebrow label: <span class="nk-eyebrow" style="color:var(--nk-primary);">LABEL</span>
Prefer tight letter-spacing on big headings (-0.01 to -0.03em), loose spacing (0.15em+) on small uppercase labels.

LAYOUT RHYTHM
- Sections are full-width <section class="py-5 py-lg-6"> with a .container inside.
- Never cramp content. Use py-5 minimum between sections, py-lg-6 on larger screens.
- Hero sections get py-6 py-lg-7 and usually feature a two-column split (.col-lg-6 .col-lg-6).
- Stack cards in .row .g-4 or .g-5. Use col-md-4 (3-up) or col-md-6 (2-up) responsively.
- Alternate section backgrounds: use var(--nk-bg) and var(--nk-surface-2) on alternate sections for visual rhythm.

DECORATIVE VISUAL TRICKS (use these to add personality)
- Giant background text: add oversized, near-invisible text behind a section for visual depth:
  <div class="position-absolute top-50 start-50 translate-middle text-nowrap" style="font-size:12rem;font-weight:800;opacity:0.03;color:var(--nk-text);pointer-events:none;z-index:0;">KEYWORD</div>
- Gradient blobs: subtle radial backgrounds behind hero sections (see HERO PATTERN).
- Pill badges: <span class="badge rounded-pill px-3 py-2" style="background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-size:0.75rem;font-weight:600;letter-spacing:0.05em;">Label</span>
- Separator dots between inline items: use &#183; or <span style="opacity:0.3;">|</span>

=======================================
SECTION PATTERNS — pick from these
=======================================

HERO PATTERN (use on home pages)
Structure: background band with two subtle gradient blobs → eyebrow label → large display heading → lead paragraph → two CTAs (one primary filled, one outlined) → optional visual (card stack, image, form card) on the right.

<section class="position-relative overflow-hidden py-6 py-lg-7">
  <div class="position-absolute top-0 start-0 translate-middle rounded-circle" style="width:420px;height:420px;background:var(--nk-primary);opacity:0.18;filter:blur(100px);"></div>
  <div class="position-absolute bottom-0 end-0 translate-middle-x rounded-circle" style="width:380px;height:380px;background:var(--nk-accent);opacity:0.16;filter:blur(100px);"></div>
  <div class="container position-relative">
    <div class="row align-items-center g-5">
      <div class="col-lg-7">
        <span class="nk-eyebrow mb-3 d-inline-block" style="color:var(--nk-primary);">EYEBROW LABEL</span>
        <h1 class="display-3 fw-bold mb-3" style="letter-spacing:-0.025em;line-height:1.05;">Your headline here.</h1>
        <p class="lead mb-4" style="color:var(--nk-text-muted);max-width:560px;">One friendly sentence that explains what this app does.</p>
        <div class="d-flex flex-wrap gap-3">
          <a href="/primary-slug" class="btn btn-primary btn-lg px-4">Primary CTA</a>
          <a href="/secondary-slug" class="btn btn-outline-primary btn-lg px-4">Secondary CTA</a>
        </div>
      </div>
      <div class="col-lg-5">
        <!-- right column: a card, a form, an image, a stat block, or a data list -->
      </div>
    </div>
  </div>
</section>

CARD GRID PATTERN (use for features, listings, data-bound rows)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold mb-2" style="letter-spacing:-0.01em;">Section title</h2>
      <p class="lead mx-auto" style="color:var(--nk-text-muted);max-width:560px;">One-line section description.</p>
    </div>
    <div class="row g-4">
      <div class="col-md-4">
        <div class="h-100 p-4" style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);transition:transform .2s,box-shadow .2s;">
          <div class="nk-icon-chip mb-3" style="background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);">★</div>
          <h3 class="h5 fw-bold mb-2">Feature title</h3>
          <p class="small mb-0" style="color:var(--nk-text-muted);">Short feature description in one or two lines.</p>
        </div>
      </div>
      <!-- more .col-md-4 cards -->
    </div>
  </div>
</section>

ALTERNATING FEATURE ROWS (use for "about" or "how it works" when you want more detail per feature — alternate image left/right)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="row align-items-center g-5 mb-5">
      <div class="col-lg-6">
        <div style="aspect-ratio:4/3;background:linear-gradient(135deg, var(--nk-primary), var(--nk-accent));border-radius:var(--nk-radius);"></div>
      </div>
      <div class="col-lg-6">
        <span class="nk-eyebrow mb-2 d-inline-block" style="color:var(--nk-primary);">FEATURE ONE</span>
        <h3 class="display-6 fw-bold mb-3">Feature headline</h3>
        <p style="color:var(--nk-text-muted);">Detailed paragraph explaining this feature in 2-3 sentences.</p>
        <a href="#" style="color:var(--nk-primary);font-weight:600;text-decoration:none;">Learn more →</a>
      </div>
    </div>
    <!-- Next row: swap col order with .order-lg-2 on image for right-side image -->
    <div class="row align-items-center g-5">
      <div class="col-lg-6 order-lg-2">
        <div style="aspect-ratio:4/3;background:linear-gradient(135deg, var(--nk-accent), var(--nk-primary));border-radius:var(--nk-radius);"></div>
      </div>
      <div class="col-lg-6">
        <span class="nk-eyebrow mb-2 d-inline-block" style="color:var(--nk-primary);">FEATURE TWO</span>
        <h3 class="display-6 fw-bold mb-3">Another headline</h3>
        <p style="color:var(--nk-text-muted);">Another detailed paragraph.</p>
        <a href="#" style="color:var(--nk-primary);font-weight:600;text-decoration:none;">Learn more →</a>
      </div>
    </div>
  </div>
</section>

PRICING TABLE PATTERN (use for plans/packages — highlight the recommended plan; prices you weren't given stay as [Price] placeholders)
<section class="py-5 py-lg-6" style="background:var(--nk-surface-2);">
  <div class="container">
    <div class="text-center mb-5">
      <span class="badge rounded-pill px-3 py-2 mb-3" style="background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-weight:600;">Pricing</span>
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Choose your plan</h2>
    </div>
    <div class="row g-4 justify-content-center align-items-end">
      <!-- Basic -->
      <div class="col-lg-4 col-md-6">
        <div class="text-center p-4 p-lg-5" style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);">
          <div class="text-uppercase fw-semibold small mb-2" style="color:var(--nk-text-muted);letter-spacing:0.1em;">Basic</div>
          <div class="display-5 fw-bold mb-1">[Price]</div>
          <div class="small mb-4" style="color:var(--nk-text-muted);">per month</div>
          <ul class="list-unstyled mb-4" style="color:var(--nk-text-muted);">
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">What's included</li>
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">Another inclusion</li>
            <li class="py-2">One more</li>
          </ul>
          <a href="#" class="btn btn-outline-primary btn-lg w-100 px-4">Get started</a>
        </div>
      </div>
      <!-- Pro (highlighted) -->
      <div class="col-lg-4 col-md-6">
        <div class="text-center p-4 p-lg-5 position-relative" style="background:var(--nk-surface);border:2px solid var(--nk-primary);border-radius:var(--nk-radius);box-shadow:0 20px 60px color-mix(in srgb, var(--nk-primary) 20%, transparent);">
          <span class="badge position-absolute top-0 start-50 translate-middle rounded-pill px-3 py-2" style="background:var(--nk-primary);color:var(--nk-on-primary);font-weight:600;">Popular</span>
          <div class="text-uppercase fw-semibold small mb-2" style="color:var(--nk-primary);letter-spacing:0.1em;">Pro</div>
          <div class="display-5 fw-bold mb-1">[Price]</div>
          <div class="small mb-4" style="color:var(--nk-text-muted);">per month</div>
          <ul class="list-unstyled mb-4" style="color:var(--nk-text-muted);">
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">Everything in Basic</li>
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">What this plan adds</li>
            <li class="py-2">One more</li>
          </ul>
          <a href="#" class="btn btn-primary btn-lg w-100 px-4">Get started</a>
        </div>
      </div>
      <!-- Enterprise -->
      <div class="col-lg-4 col-md-6">
        <div class="text-center p-4 p-lg-5" style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);">
          <div class="text-uppercase fw-semibold small mb-2" style="color:var(--nk-text-muted);letter-spacing:0.1em;">Enterprise</div>
          <div class="display-5 fw-bold mb-1">[Price]</div>
          <div class="small mb-4" style="color:var(--nk-text-muted);">per month</div>
          <ul class="list-unstyled mb-4" style="color:var(--nk-text-muted);">
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">Everything in Pro</li>
            <li class="py-2" style="border-bottom:1px solid var(--nk-border);">What this plan adds</li>
            <li class="py-2">One more</li>
          </ul>
          <a href="#" class="btn btn-outline-primary btn-lg w-100 px-4">Contact us</a>
        </div>
      </div>
    </div>
  </div>
</section>

TESTIMONIAL PATTERN (ONLY for real quotes the request supplies, or bound with data-nk-bind-flow-ref to a reviews table real visitors fill in — never invent quotes, names or ratings)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">What people say</h2>
    </div>
    <div class="row g-4">
      <div class="col-md-4">
        <div class="p-4 position-relative" style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);">
          <p class="mb-0" style="color:var(--nk-text-muted);">"[The customer's own words]"</p>
        </div>
        <div class="d-flex align-items-center mt-3 ps-2">
          <div class="rounded-circle d-flex align-items-center justify-content-center fw-bold" style="width:48px;height:48px;background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-size:1.1rem;flex-shrink:0;" aria-hidden="true">A</div>
          <div class="ms-3">
            <div class="fw-semibold small">[Customer name]</div>
          </div>
        </div>
      </div>
      <!-- more .col-md-4 testimonial cards -->
    </div>
  </div>
</section>

TEAM SECTION PATTERN (use for "our team" or "meet the crew" — names and roles you weren't given stay as [Name] and [Role])
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Our team</h2>
      <p class="lead mx-auto" style="color:var(--nk-text-muted);max-width:480px;">The people behind the product.</p>
    </div>
    <div class="row g-4">
      <div class="col-md-4 col-lg-3 text-center">
        <div class="rounded-circle mx-auto mb-3" style="width:120px;height:120px;background:linear-gradient(135deg, var(--nk-primary), var(--nk-accent));" aria-hidden="true"></div>
        <h4 class="h6 fw-bold mb-1">[Name]</h4>
        <div class="small" style="color:var(--nk-text-muted);">[Role]</div>
      </div>
      <!-- more .col-md-4.col-lg-3 team members -->
    </div>
  </div>
</section>

PROCESS / HOW IT WORKS PATTERN (numbered steps with connector — use for onboarding, process)
<section class="py-5 py-lg-6" style="background:var(--nk-surface-2);">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">How it works</h2>
    </div>
    <div class="row g-4 position-relative">
      <!-- Connector line (desktop only) -->
      <div class="d-none d-md-block position-absolute" style="top:32px;left:16.67%;right:16.67%;height:2px;background:var(--nk-border);z-index:0;"></div>
      <div class="col-md-4 text-center position-relative" style="z-index:1;">
        <div class="rounded-circle d-inline-flex align-items-center justify-content-center fw-bold mb-3" style="width:64px;height:64px;background:var(--nk-primary);color:var(--nk-on-primary);font-size:1.25rem;">1</div>
        <h4 class="h5 fw-bold mb-2">Sign up</h4>
        <p class="small mx-auto" style="color:var(--nk-text-muted);max-width:260px;">Create your account in under a minute.</p>
      </div>
      <div class="col-md-4 text-center position-relative" style="z-index:1;">
        <div class="rounded-circle d-inline-flex align-items-center justify-content-center fw-bold mb-3" style="width:64px;height:64px;background:var(--nk-primary);color:var(--nk-on-primary);font-size:1.25rem;">2</div>
        <h4 class="h5 fw-bold mb-2">Customize</h4>
        <p class="small mx-auto" style="color:var(--nk-text-muted);max-width:260px;">Choose your preferences and set up your profile.</p>
      </div>
      <div class="col-md-4 text-center position-relative" style="z-index:1;">
        <div class="rounded-circle d-inline-flex align-items-center justify-content-center fw-bold mb-3" style="width:64px;height:64px;background:var(--nk-primary);color:var(--nk-on-primary);font-size:1.25rem;">3</div>
        <h4 class="h5 fw-bold mb-2">Launch</h4>
        <p class="small mx-auto" style="color:var(--nk-text-muted);max-width:260px;">Go live and start seeing results.</p>
      </div>
    </div>
  </div>
</section>

FACTS STRIP PATTERN (ONLY with numbers or facts the request supplies — otherwise leave it out; never invent counts, percentages or ratings)
<section class="py-5" style="border-top:1px solid var(--nk-border);border-bottom:1px solid var(--nk-border);">
  <div class="container">
    <div class="row g-4 text-center">
      <div class="col-6 col-md-3">
        <div class="display-5 fw-bold" style="color:var(--nk-primary);letter-spacing:-0.02em;">[Fact]</div>
        <div class="small text-uppercase fw-semibold mt-1" style="color:var(--nk-text-muted);letter-spacing:0.15em;">[Label]</div>
      </div>
      <div class="col-6 col-md-3">
        <div class="display-5 fw-bold" style="color:var(--nk-primary);letter-spacing:-0.02em;">[Fact]</div>
        <div class="small text-uppercase fw-semibold mt-1" style="color:var(--nk-text-muted);letter-spacing:0.15em;">[Label]</div>
      </div>
      <div class="col-6 col-md-3">
        <div class="display-5 fw-bold" style="color:var(--nk-primary);letter-spacing:-0.02em;">[Fact]</div>
        <div class="small text-uppercase fw-semibold mt-1" style="color:var(--nk-text-muted);letter-spacing:0.15em;">[Label]</div>
      </div>
      <div class="col-6 col-md-3">
        <div class="display-5 fw-bold" style="color:var(--nk-primary);letter-spacing:-0.02em;">[Fact]</div>
        <div class="small text-uppercase fw-semibold mt-1" style="color:var(--nk-text-muted);letter-spacing:0.15em;">[Label]</div>
      </div>
    </div>
  </div>
</section>

FAQ / ACCORDION PATTERN (use for FAQs, common questions — two-column with heading on left; answers about the business you weren't given stay as [Your answer])
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="row g-5">
      <div class="col-lg-5">
        <span class="nk-eyebrow mb-2 d-inline-block" style="color:var(--nk-primary);">FAQ</span>
        <h2 class="display-5 fw-bold mb-3" style="letter-spacing:-0.01em;">Common questions</h2>
        <p style="color:var(--nk-text-muted);">Can't find what you're looking for? Reach out to our support team.</p>
        <a href="/contact" class="btn btn-outline-primary mt-2">Contact us</a>
      </div>
      <div class="col-lg-7">
        <div class="accordion" id="faq">
          <div class="py-3" style="border-bottom:1px solid var(--nk-border);">
            <button class="btn p-0 w-100 text-start d-flex justify-content-between align-items-center fw-semibold" style="color:var(--nk-text);" data-bs-toggle="collapse" data-bs-target="#faq1">
              How does it work?
              <span style="color:var(--nk-text-muted);">+</span>
            </button>
            <div class="collapse mt-2" id="faq1">
              <p class="small mb-0" style="color:var(--nk-text-muted);">[Your answer]</p>
            </div>
          </div>
          <div class="py-3" style="border-bottom:1px solid var(--nk-border);">
            <button class="btn p-0 w-100 text-start d-flex justify-content-between align-items-center fw-semibold" style="color:var(--nk-text);" data-bs-toggle="collapse" data-bs-target="#faq2">
              Can I cancel anytime?
              <span style="color:var(--nk-text-muted);">+</span>
            </button>
            <div class="collapse mt-2" id="faq2">
              <p class="small mb-0" style="color:var(--nk-text-muted);">[Your answer]</p>
            </div>
          </div>
          <!-- more items -->
        </div>
      </div>
    </div>
  </div>
</section>

TAB CONTENT PATTERN (use for menus, service categories, feature groups — tabs switch content panels)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Our menu</h2>
    </div>
    <ul class="nav nav-pills justify-content-center gap-2 mb-5" role="tablist">
      <li class="nav-item"><a class="nav-link active rounded-pill px-4" data-bs-toggle="tab" href="#tab1">Category 1</a></li>
      <li class="nav-item"><a class="nav-link rounded-pill px-4" data-bs-toggle="tab" href="#tab2">Category 2</a></li>
      <li class="nav-item"><a class="nav-link rounded-pill px-4" data-bs-toggle="tab" href="#tab3">Category 3</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade show active" id="tab1">
        <div class="row g-4">
          <!-- items for this category -->
        </div>
      </div>
      <div class="tab-pane fade" id="tab2">
        <div class="row g-4"><!-- items --></div>
      </div>
      <div class="tab-pane fade" id="tab3">
        <div class="row g-4"><!-- items --></div>
      </div>
    </div>
  </div>
</section>

GALLERY / PORTFOLIO GRID PATTERN (use for image galleries, project showcases)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Gallery</h2>
    </div>
    <div class="row g-3">
      <div class="col-md-4">
        <div class="position-relative overflow-hidden" style="aspect-ratio:1;border-radius:var(--nk-radius);background:linear-gradient(135deg, var(--nk-primary), var(--nk-accent));">
        </div>
      </div>
      <div class="col-md-4">
        <div class="position-relative overflow-hidden" style="aspect-ratio:1;border-radius:var(--nk-radius);background:linear-gradient(135deg, var(--nk-accent), var(--nk-primary));">
        </div>
      </div>
      <div class="col-md-4">
        <div class="position-relative overflow-hidden" style="aspect-ratio:1;border-radius:var(--nk-radius);background:linear-gradient(45deg, var(--nk-primary), var(--nk-accent));">
        </div>
      </div>
    </div>
  </div>
</section>

CLIENT / PARTNER STRIP PATTERN (ONLY with real client or partner names the request supplies — never invent brands)
<section class="py-4" style="border-top:1px solid var(--nk-border);">
  <div class="container">
    <div class="text-center small text-uppercase fw-semibold mb-3" style="color:var(--nk-text-muted);letter-spacing:0.15em;">Trusted by</div>
    <div class="d-flex flex-wrap justify-content-center align-items-center gap-4 gap-lg-5" style="opacity:0.5;">
      <span class="fw-bold" style="font-size:1.25rem;color:var(--nk-text);">[Partner name]</span>
      <span class="fw-bold" style="font-size:1.25rem;color:var(--nk-text);">[Partner name]</span>
      <span class="fw-bold" style="font-size:1.25rem;color:var(--nk-text);">[Partner name]</span>
      <span class="fw-bold" style="font-size:1.25rem;color:var(--nk-text);">[Partner name]</span>
      <span class="fw-bold" style="font-size:1.25rem;color:var(--nk-text);">[Partner name]</span>
    </div>
  </div>
</section>

CTA BAND PATTERN (use near the bottom of home / landing pages)
<section class="py-5 py-lg-6">
  <div class="container">
    <div class="p-5 p-lg-6 text-center position-relative overflow-hidden" style="border-radius:calc(var(--nk-radius) + 6px);background:linear-gradient(135deg, color-mix(in srgb, var(--nk-primary) 95%, black), color-mix(in srgb, var(--nk-accent) 80%, black));color:#fff;">
      <h2 class="display-5 fw-bold mb-2" style="letter-spacing:-0.01em;">Ready to get started?</h2>
      <p class="lead mb-4" style="opacity:0.9;">Short friendly nudge telling the user what to do next.</p>
      <a href="/primary-slug" class="btn btn-lg px-4" style="background:#fff;color:var(--nk-primary);border-radius:var(--nk-radius-sm);">Call to action</a>
    </div>
  </div>
</section>

FORM CARD PATTERN (use for contact, signup, booking forms)
<form data-nk-form="" data-nk-flow-ref="slug" class="p-4 p-lg-5" style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);">
  <div class="mb-4">
    <h3 class="h4 fw-bold mb-1">Form title</h3>
    <p class="small mb-0" style="color:var(--nk-text-muted);">One-line helper text.</p>
  </div>
  <div class="row g-3">
    <div class="col-md-6"><label class="form-label small fw-semibold">Your name</label><input name="name" class="form-control form-control-lg" required/></div>
    <div class="col-md-6"><label class="form-label small fw-semibold">Email</label><input name="email" type="email" class="form-control form-control-lg" required/></div>
    <div class="col-12"><label class="form-label small fw-semibold">Message</label><textarea name="message" class="form-control form-control-lg" rows="4"></textarea></div>
    <div class="col-12 d-grid"><button class="btn btn-primary btn-lg" type="submit">Send message</button></div>
  </div>
  <div data-nk-error class="text-danger small mt-3"></div>
</form>

SPLIT FEATURE SECTION (use for "why choose us" / benefits + form side by side)
<section class="py-5 py-lg-6" style="background:var(--nk-surface-2);">
  <div class="container">
    <div class="row g-5 align-items-center">
      <div class="col-lg-6">
        <span class="nk-eyebrow mb-2 d-inline-block" style="color:var(--nk-primary);">WHY CHOOSE US</span>
        <h2 class="display-5 fw-bold mb-4" style="letter-spacing:-0.01em;">Built for your success</h2>
        <div class="d-flex align-items-start mb-3">
          <div class="rounded-circle d-flex align-items-center justify-content-center flex-shrink-0 me-3" style="width:32px;height:32px;background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-size:14px;">✓</div>
          <div><h5 class="h6 fw-bold mb-1">Benefit title</h5><p class="small mb-0" style="color:var(--nk-text-muted);">One-line explanation.</p></div>
        </div>
        <div class="d-flex align-items-start mb-3">
          <div class="rounded-circle d-flex align-items-center justify-content-center flex-shrink-0 me-3" style="width:32px;height:32px;background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-size:14px;">✓</div>
          <div><h5 class="h6 fw-bold mb-1">Another benefit</h5><p class="small mb-0" style="color:var(--nk-text-muted);">One-line explanation.</p></div>
        </div>
        <!-- more benefits -->
      </div>
      <div class="col-lg-6">
        <!-- Form card or booking form here, on a solid accent bg -->
        <form data-nk-form="" data-nk-flow-ref="slug" class="p-4 p-lg-5" style="background:var(--nk-primary);border-radius:var(--nk-radius);color:var(--nk-on-primary);">
          <h3 class="h4 fw-bold mb-4" style="color:#fff;">Book now</h3>
          <div class="row g-3">
            <div class="col-md-6"><input name="name" class="form-control form-control-lg" placeholder="Your name" required style="border:none;border-bottom:2px solid rgba(255,255,255,0.3);border-radius:0;background:transparent;color:#fff;"/></div>
            <div class="col-md-6"><input name="email" type="email" class="form-control form-control-lg" placeholder="Email" required style="border:none;border-bottom:2px solid rgba(255,255,255,0.3);border-radius:0;background:transparent;color:#fff;"/></div>
            <div class="col-12 d-grid"><button class="btn btn-lg" type="submit" style="background:#fff;color:var(--nk-primary);">Submit</button></div>
          </div>
          <div data-nk-error class="small mt-3" style="color:rgba(255,255,255,0.8);"></div>
        </form>
      </div>
    </div>
  </div>
</section>

SCHEDULE / TIMETABLE PATTERN (use for class schedules, event agendas, session lists)
<section class="py-5 py-lg-6">
  <div class="container" style="max-width:800px;">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Schedule</h2>
    </div>
    <div class="py-3 d-flex align-items-center justify-content-between" style="border-bottom:1px solid var(--nk-border);">
      <div>
        <div class="small fw-semibold" style="color:var(--nk-primary);">[Time]</div>
        <h4 class="h6 fw-bold mb-0 mt-1">Session title</h4>
        <div class="small" style="color:var(--nk-text-muted);">[Instructor name]</div>
      </div>
      <span class="badge rounded-pill px-3 py-2" style="background:color-mix(in srgb, var(--nk-primary) 12%, transparent);color:var(--nk-primary);font-size:0.7rem;">Room A</span>
    </div>
    <!-- more sessions -->
  </div>
</section>

MENU / PRICE LIST PATTERN (use for restaurants, spas, service menus — item + dotted line + price)
<section class="py-5 py-lg-6">
  <div class="container" style="max-width:720px;">
    <div class="text-center mb-5">
      <h2 class="display-5 fw-bold" style="letter-spacing:-0.01em;">Our menu</h2>
    </div>
    <div class="mb-4">
      <div class="d-flex justify-content-between align-items-baseline py-3" style="border-bottom:1px dashed var(--nk-border);">
        <div>
          <h4 class="h6 fw-bold mb-0">Item name</h4>
          <p class="small mb-0" style="color:var(--nk-text-muted);">Short description of the item.</p>
        </div>
        <div class="fw-bold ms-3 text-nowrap" style="color:var(--nk-primary);">[Price]</div>
      </div>
      <!-- more items -->
    </div>
  </div>
</section>

FOOTER PATTERN
Always end a home page with a footer:
<footer class="py-5 mt-5" style="border-top:1px solid var(--nk-border);">
  <div class="container">
    <div class="row g-4 align-items-center">
      <div class="col-md-6">
        <div class="fw-bold mb-1">Brand name</div>
        <div class="small" style="color:var(--nk-text-muted);">One-line tagline.</div>
      </div>
      <div class="col-md-6 text-md-end">
        <a class="me-3 small" href="/about" style="color:var(--nk-text-muted);text-decoration:none;">About</a>
        <a class="me-3 small" href="/contact" style="color:var(--nk-text-muted);text-decoration:none;">Contact</a>
        <a class="small" href="/terms" style="color:var(--nk-text-muted);text-decoration:none;">Terms</a>
      </div>
    </div>
  </div>
</footer>

=======================================
PAGE COMPOSITION — which sections to use
=======================================

HOME PAGE (pick 5-8 sections, always start with hero and end with footer):
Hero → Features (card grid OR alternating rows) → How It Works (process) → Pricing or menu (if relevant) → FAQ → CTA Band → Footer
Add testimonials, a facts strip or partner names only when the request supplies real ones.

ABOUT PAGE:
Hero (shorter) → Story (what the business does and for whom) → Process/Timeline → Team (names as placeholders unless given) → CTA Band → Footer

SERVICES / FEATURES PAGE:
Hero (shorter) → Card Grid → Alternating Feature Rows → Pricing → FAQ → CTA Band → Footer

CONTACT PAGE:
Hero (shorter, with contact form on right) → Footer

BLOG / LISTINGS PAGE:
Hero (shorter) → Card Grid (data-bound) → Footer

=======================================
INDUSTRY PERSONALITY GUIDE
=======================================

Match the app's tone to its industry. The THEME handles colors/fonts, but YOU control the vibe through copy, section choices, and decorative details:

FOOD / RESTAURANT / CAFE:
- Warm, inviting language ("Handcrafted with love", "Savor every bite")
- Use the MENU/PRICE LIST pattern for dishes with dotted-line pricing
- TAB CONTENT pattern for menu categories (Appetizers / Mains / Desserts)
- Circular avatar-style food images
- Generous padding, relaxed feel

SAAS / TECH / STARTUP:
- Clean, confident language ("Ship faster", "Built for scale")
- PRICING TABLE is essential
- PROCESS steps for "How it works"
- Tight, dense cards with lots of features

FITNESS / HEALTH / YOGA:
- Calm, empowering language ("Find your balance", "Transform your body")
- Large images, spacious layouts
- PROCESS for class schedule or session flow
- FAQ for first-timers' questions
- Organic rounded shapes, soft gradients

CREATIVE / PORTFOLIO / AGENCY:
- Bold, minimal language ("We make things beautiful")
- GALLERY grid is essential
- Larger typography, more whitespace
- ALTERNATING FEATURE ROWS for case studies
- Dark backgrounds work well (use var(--nk-surface))

PROFESSIONAL / CONSULTING / LAW:
- Authoritative language ("Trusted expertise", "Results that matter")
- TEAM section is essential
- FAQ for common legal/financial questions
- Conservative spacing, professional feel

ECOMMERCE / SHOP:
- Action-oriented language ("Shop now", "New arrivals")
- CARD GRID for product listings (data-bound)
- TAB CONTENT for categories
- A reviews list bound to real reviews (data-nk-bind-flow-ref) when the app collects them
- PRICING patterns for subscription boxes

BOOKING / SERVICE:
- Friendly, service-oriented ("Book your spot", "We'll take care of the rest")
- PROCESS for how booking works
- FORM CARD prominent on home page
- PRICING for packages
- FAQ for what to expect

BUTTON RULES
- Primary CTA: class="btn btn-primary btn-lg px-4" — never override its background inline
- Secondary CTA: class="btn btn-outline-primary btn-lg px-4"
- Link-style: class="btn btn-link px-0" style="color:var(--nk-primary);"
- Pills: class="btn btn-primary btn-lg rounded-pill px-4"

ICON RULES
Use unicode symbols or inline SVG (stroke-width:2, size 20-24) — never external icon fonts. Put the icon in a rounded colored chip: style="width:48px;height:48px;display:inline-flex;align-items:center;justify-content:center;border-radius:var(--nk-radius-sm);background:color-mix(in srgb, var(--nk-primary) 15%, transparent);color:var(--nk-primary);font-size:22px;"

IMAGE RULES
- Pictures come only from the images listed under AVAILABLE LOCAL IMAGES, image URLs the user supplied, or pictures already on the page. Never use outside photo sites (stock-photo, placeholder or random-image services) and never invent image URLs or local photo paths.
- When no suitable image is supplied, create an original inline SVG or a purposeful CSS composition. Use descriptive alt text for content images; mark decorative artwork aria-hidden.
- For data-bound lists, use data-nk-src="column_name" on the <img> so the runtime fills it in from DB rows.

DO NOT
- Do not use bg-white, bg-light, bg-dark, bg-primary, text-white, text-dark, text-primary utilities — they bypass the theme.
- Do not hardcode hex colors or rgb() values.
- Do not use <style> blocks with @import — theme CSS already loads fonts.
- Do not omit hero sections on home pages. Every home page needs a hero.
- Do not produce pages with no footer.
- Do not use rounded-0 anywhere — respect var(--nk-radius).
- Do not put <script> tags in page HTML unless the page genuinely needs browser-side logic (games, canvas, drag and drop). Saving and loading data always goes through forms and flows, never hand-written fetch code.
- Do not build every app the same way. Match sections and tone to the industry (see PERSONALITY GUIDE above).
- Do not use emoji anywhere — not in headings, buttons, feature cards, or copy. Monochrome glyphs (★ ✓ ✕ arrows) are fine where they carry meaning (ratings, checkmarks); colored pictographic emoji are never acceptable.
`;

/**
 * The same design direction in ~2K characters, for models with small context
 * windows (see ai/budget.ts). Keeps the rules that most affect quality and
 * theming; drops the long pattern catalogue.
 */
export const DESIGN_RULES_COMPACT = `DESIGN RULES
- Look: a polished, premium website that suits the industry — warm and inviting for food, clean and precise for software, calm for wellness, bold for creative work, authoritative for professional services.
- Colours, fonts and corners ONLY through theme variables: var(--nk-primary) for buttons and links, var(--nk-primary-2), var(--nk-accent), var(--nk-surface) for cards, var(--nk-surface-2) for alternating bands, var(--nk-border), var(--nk-text), var(--nk-text-muted), var(--nk-radius), var(--nk-radius-sm). Never write hex or rgb() colours; never use Bootstrap colour classes (bg-*, text-white, text-primary).
- Layout: Bootstrap 5, mobile-first, no horizontal scrolling. <section class="py-5"><div class="container"><div class="row g-4"> with col-md-6 or col-md-4 columns.
- Home page: hero (one h1, a one-sentence lead, a primary and a secondary button) → 3-5 sections that fit the industry (features, menu with prices, services, schedule, pricing, FAQ) → a call-to-action band → footer. Other pages: short heading band → content → footer.
- Headings: one h1 per page, h2 per section, h3 in cards. Buttons: class="btn btn-primary btn-lg" and "btn btn-outline-primary btn-lg".
- Cards: style="background:var(--nk-surface);border:1px solid var(--nk-border);border-radius:var(--nk-radius);padding:1.5rem".
- Icons: small inline SVG (viewBox="0 0 24 24", stroke="currentColor", fill="none"). No emoji, no icon fonts, no invented image URLs.
- Pictures: only the images listed under AVAILABLE LOCAL IMAGES or image URLs the user supplied, or CSS gradients. Never use outside photo sites.
- Copy: specific to this business, in plain words. No lorem ipsum.
- Honesty: never invent testimonials, reviews, star ratings, customer counts, awards or certifications; leave stats out unless given; prices, hours or phone numbers you weren't given are written as placeholders like [Your price].`;
