// Everything the game loads, by asset-library id (CC0 only: KayKit + Kenney).
NK.assets.define({
  // Characters (all on KayKit's rig-medium, so every clip below fits every character).
  knight: "kaykit/adventurers/characters/knight",
  mage: "kaykit/adventurers/characters/mage",
  "sk-warrior": "kaykit/skeletons/characters/skeleton-warrior",
  "sk-archer": "kaykit/skeletons/characters/skeleton-minion",
  "anim-general": "kaykit/skeletons/animations/rig-medium/rig-medium-general",
  "anim-move": "kaykit/skeletons/animations/rig-medium/rig-medium-movement-basic",
  "anim-melee": "kaykit/character-animations/animations/rig-medium/rig-medium-combat-melee",
  "anim-ranged": "kaykit/character-animations/animations/rig-medium/rig-medium-combat-ranged",
  // Hand-held gear (attached to the rigs' handslot bones).
  sword: "kaykit/adventurers/sword-1handed",
  shield: "kaykit/adventurers/shield-badge-color",
  staff: "kaykit/adventurers/staff",
  bow: "kaykit/adventurers/bow-with-string",
  "sk-blade": "kaykit/skeletons/skeleton-blade",
  "sk-shield": "kaykit/skeletons/skeleton-shield-small-a",
  arrow: "kaykit/skeletons/skeleton-arrow",

  // The hall (KayKit Dungeon Pack: 4 m wall modules, 2 m floor tiles).
  floor: "kaykit/dungeon-pack/floor-tile-small",
  "floor-broken-a": "kaykit/dungeon-pack/floor-tile-small-broken-a",
  "floor-broken-b": "kaykit/dungeon-pack/floor-tile-small-broken-b",
  wall: "kaykit/dungeon-pack/wall",
  "wall-pillar": "kaykit/dungeon-pack/wall-pillar",
  "wall-gated": "kaykit/dungeon-pack/wall-gated",
  "wall-arch": "kaykit/dungeon-pack/wall-doorway-sides",
  "wall-inset": "kaykit/dungeon-pack/wall-inset-candles",
  block: "kaykit/dungeon-pack/floor-foundation-allsides",
  "block-front": "kaykit/dungeon-pack/floor-foundation-front",
  column: "kaykit/dungeon-pack/column",
  pillar: "kaykit/dungeon-pack/pillar",
  torch: "kaykit/dungeon-pack/torch-mounted",
  "banner-vault": "kaykit/dungeon-pack/banner-shield-red",
  chest: "kaykit/dungeon-pack/chest-large",
  "coins-large": "kaykit/dungeon-pack/coin-stack-large",
  "coins-medium": "kaykit/dungeon-pack/coin-stack-medium",
  crates: "kaykit/dungeon-pack/crates-stacked",
  "box-large": "kaykit/dungeon-pack/box-large",
  "box-small": "kaykit/dungeon-pack/box-small",
  "crate-open": "kaykit/dungeon-pack/crate-large",
  barrel: "kaykit/dungeon-pack/barrel-large",
  "barrel-small": "kaykit/dungeon-pack/barrel-small",
  "barrel-stack": "kaykit/dungeon-pack/barrel-small-stack",
  keg: "kaykit/dungeon-pack/keg",
  bucket: "kaykit/dungeon-pack/bucket",
  shelf: "kaykit/dungeon-pack/shelf-large",
  post: "kaykit/dungeon-pack/post",
  rubble: "kaykit/dungeon-pack/rocks-small",
  "candle-triple": "kaykit/dungeon-pack/candle-triple",
  spear: "kaykit/fantasy-weapons-bits/spear-a",
  halberd: "kaykit/fantasy-weapons-bits/halberd",
  chain: "kaykit/mixed-bag-1/chain-hanging-a",
  lantern: "kaykit/halloween-bits/lantern-hanging",
  bones: "kaykit/halloween-bits/bone-a",
  skull: "kaykit/halloween-bits/skull",

  // HUD icons (white silhouettes, tinted by CSS masks in src/ui/hud.js).
  "icon-heart": "kenney/board-game-icons/double/suit-hearts",
  "icon-sword": "kenney/board-game-icons/double/sword",
  "icon-bolt": "kenney/board-game-icons/double/exploding",
  "icon-shield": "kenney/board-game-icons/double/shield",
  "icon-flask": "kenney/board-game-icons/double/flask-full",
  "icon-flask-glass": "kenney/board-game-icons/double/flask-empty",
  "icon-pause": "kenney/mobile-controls/icon-pause",

  // Sound.
  "sfx-swing": "kenney/foley-sounds/swords/sword1",
  "sfx-hit": "kenney/foley-sounds/swords/hit-helmet1",
  "sfx-hit2": "kenney/foley-sounds/swords/hit-helmet3",
  "sfx-block": "kenney/foley-sounds/swords/sword-metal1",
  "sfx-magic": "kenney/new-platformer-pack/sounds/sfx-magic",
  "sfx-bow": "kenney/rpg-audio/draw-knife2",
  "sfx-hurt": "kenney/retro-sounds-2/hurt1",
  "sfx-bones": "kenney/foley-sounds/rocks/rock-hit2",
  "sfx-potion": "kenney/rpg-audio/cloth-belt",
  "sfx-chest": "kenney/rpg-audio/door-open-2",
  "sfx-coins": "kenney/rpg-audio/handle-coins",
  "sfx-locked": "kenney/rpg-audio/metal-latch",
  "sfx-step": "kenney/rpg-audio/footstep02",
  "sfx-drip": "kenney/foley-sounds/water/drip2",
  "sfx-win": "kenney/music-jingles/audio-pizzicato/jingles-pizzicato-05",
  "ui-click": "kenney/interface-sounds/click-001",
  music: "kenney/music-loops/loops/infinite-descent",
});
